# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'
      cluster:  pulsar_pseudo_cluster

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:19093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
         - targets: ['docker.for.mac.localhost:19090']

  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['docker.for.mac.localhost:48080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
  
    static_configs:
      - targets: ['docker.for.mac.localhost:19100']

  - job_name: "broker"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
      - targets:
        - 'docker.for.mac.localhost:18080'
        - 'docker.for.mac.localhost:28080'

  - job_name: "bookie"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
      - targets:
        - 'docker.for.mac.localhost:18004'
        - 'docker.for.mac.localhost:18005'
        - 'docker.for.mac.localhost:18006'

  - job_name: "zookeeper"
    honor_labels: true
    static_configs:
      - targets:
        - 'docker.for.mac.localhost:18001'
        - 'docker.for.mac.localhost:18002'
        - 'docker.for.mac.localhost:18003'