{
 "title": "Broker Load Balance-v2",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "{cluster=~\".+\"}"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "pulsar_lb_memory_usage{cluster=~\"$cluster\", instance=~\".+\"}"
    }
   },
   {
    "name": "cache",
    "label": "Cache Name",
    "query": {
     "query": "caffeine_cache_hit_count{cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LoadBalance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pulsar_lb_bandwidth_out_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bandwidth_in_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_memory_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_directMemory_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bundles_split_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bundles_split_count{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_unload_bundle_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_unload_bundle_count{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_unload_broker_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_unload_broker_count{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pulsar_topics_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_topics_count{cluster=\"$cluster\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "caffeine_cache_estimated_size{cache=~\"owned-bundles\"}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(caffeine_cache_estimated_size{cluster=\"$cluster\",instance=~\"$instance\",cache=~\"owned-bundles\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LoadBalance Extension -- Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "pulsar_lb_resource_usage -- max_ema",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 *  pulsar_lb_resource_usage{cluster=\"$cluster\",instance=~\"$instance\", feature=\"max_ema\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_resource_usage_stats -- avg",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 * pulsar_lb_resource_usage_stats{cluster=\"$cluster\",instance=~\"$instance\", feature=\"max_ema\", stat=\"avg\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_resource_usage_stats -- std",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pulsar_lb_resource_usage_stats{cluster=\"$cluster\",instance=~\"$instance\", feature=\"max_ema\", stat=\"std\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_assign_broker_breakdown_count -- success",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pulsar_lb_assign_broker_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Success\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_assign_broker_breakdown_count -- skip",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pulsar_lb_assign_broker_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Skip\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_assign_broker_breakdown_count -- failure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pulsar_lb_assign_broker_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_unload_broker_breakdown_count -- success",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_unload_broker_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Success\"}) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_unload_broker_breakdown_count -- skip",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_unload_broker_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Skip\"}) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_unload_broker_breakdown_count -- failure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_unload_broker_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_bundles_split_breakdown_count -- success_by_reason",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_bundles_split_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Success\"}) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_bundles_split_breakdown_count -- skip_by_reason",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_bundles_split_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Skip\"}) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_bundles_split_breakdown_count -- failure_by_reason",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_bundles_split_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_bundles_split_breakdown_count -- success_by_broker",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_bundles_split_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Success\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_bundles_split_breakdown_count -- skip_by_broker",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_bundles_split_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Skip\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_lb_bundles_split_breakdown_count -- failure_by_broker",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_lb_bundles_split_breakdown_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "LoadBalance Extension -- ServiceUnitStateChannel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "pulsar_sunit_state_chn_owner_lookup_count -- total_increase_by_broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_owner_lookup_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Total\"} [1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_owner_lookup_count -- failure_increase_by_broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_owner_lookup_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}[1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_owner_lookup_count -- total_increase_by_state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_owner_lookup_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Total\"} [1m])) by (state)",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_owner_lookup_count -- failure_increase_by_state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_owner_lookup_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}[1m])) by (state)",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_event_publish_ops_count -- total_increase_by_broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_event_publish_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Total\"}[1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_event_publish_ops_count -- failure_increase_by_broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_event_publish_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}[1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_event_publish_ops_count -- total_increase_by_event",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_event_publish_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Total\"} [1m])) by (event)",
       "legendFormat": "{{ event }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_event_publish_ops_count -- failure_increase_by_event",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_event_publish_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"} [1m])) by (event)",
       "legendFormat": "{{ event }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_subscribe_ops_count -- total_increase_by_broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_subscribe_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Total\"} [1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_subscribe_ops_count -- failure_increase_by_broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_subscribe_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}[1m] )) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_subscribe_ops_count -- total_increase_by_event",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_subscribe_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Total\"}[1m] )) by (event)",
       "legendFormat": "{{ event }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_subscribe_ops_count -- failure_increase_by_event",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pulsar_sunit_state_chn_subscribe_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"}[1m] )) by (event)",
       "legendFormat": "{{ event }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_inactive_broker_cleanup_ops_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_sunit_state_chn_inactive_broker_cleanup_ops_count{cluster=\"$cluster\",instance=~\"$instance\"}) by (result)",
       "legendFormat": "{{ result }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_su_tombstone_cleanup_ops_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_sunit_state_chn_su_tombstone_cleanup_ops_count{cluster=\"$cluster\",instance=~\"$instance\"} ) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_orphan_su_cleanup_ops_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_sunit_state_chn_orphan_su_cleanup_ops_count{cluster=\"$cluster\",instance=~\"$instance\"} ) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_cleanup_ops_failure_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_sunit_state_chn_cleanup_ops_count{cluster=\"$cluster\",instance=~\"$instance\",result=\"Failure\"} ) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "pulsar_sunit_state_chn_owned_su_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_sunit_state_chn_owned_su_count{cluster=\"$cluster\",instance=~\"$instance\"} ) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}