{
 "title": "JVM Metrics",
 "description": "JVM Related Metrics",
 "tags": [ "jvm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "jvm_memory_bytes_used{cluster=~\".+\"}"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "jvm_memory_bytes_used{job=~\".+\"}"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "jvm_memory_bytes_used{job=~\"$job\", instance=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$job - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$instance\"}[30s]) * 100\n\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=~\"$instance\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=~\"$instance\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_direct_bytes_max{instance=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[30s]))",
     "legendFormat": "Pause"
    }
   ]
  }
 ]
}